
services:
  config-init:
    image: alpine:latest
    volumes:
      - ./templates:/templates  # Mount your template directory
      - config_data:/config/generated  # Mount the output directory
    environment:
      - TENANT_IDS=public,statea,stateb  # List of tenant IDs, dynamically passed to script
    entrypoint: [ "sh", "-c", "/templates/generate-configs.sh" ]  # Run the script to generate files
  mdms:
    image: egovio/mdms-v2:v1.3.3-1f3649156d-52
    volumes:
      - /home/beehyv/Desktop/Projects/digit-repos/egov-mdms-data:/opt/mdms
    environment:
      JAVA_OPTS: -Xmx512m -Xms256m
      SERVER_PORT: 8094
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/postgres
      SERVER_SERVLET_CONTEXT_PATH: /egov-mdms-service
      EGOV_MDMS_CONF_PATH: /opt/mdms/data
      MASTERS_CONFIG_URL: file:///opt/mdms/master-config.json
    ports:
      - "8094:8094"
    depends_on:
      - db
  persister:
    image: egovio/egov-persister:v1.1.5-3371bc2-5
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/postgres
      KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG: "kafka:9092"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPICS_REPLICATION_FACTOR: 1
      EGOV_PERSIST_YML_REPO_PATH: file:///home/${SELECTED_SERVICE}-persister.yml
      PERSISTER_BULK_ENABLED: "false"
      #        file:///home/id-pool-persister.yml,
      #        file:///home/id-pool-dispatch-log-persister.yml
      #      EGOV_PERSIST_YML_REPO_PATH: "file:///home/id-pool-persister.yml,file:///home/id-pool-dispatch-log-persister.yml"
      LOGGING_LEVEL_ORG_EGOV_INFRA_PERSIST_REPOSITORY: DEBUG
    volumes:
      - ./backend/muster-roll/src/main/resources/muster-roll-persister.yml:/home/muster-roll-persister.yml
      - ./backend/expense/src/main/resources/expense-persister.yml:/home/expense-persister.yml
    depends_on:
      - db
      - kafka
  db-migration:
    build:
      context: ./backend/${SELECTED_SERVICE}/src/main/resources/db
      #      context: ./backend/referralmanagement/src/main/resources/db
      #      context: ./backend/facility/src/main/resources/db
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      SCHEMA_TABLE: ${SELECTED_SERVICE}_migrations
      SCHEMA_NAME: public,statea,stateb
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./backend/${SELECTED_SERVICE}/src/main/resources/db/migration/main:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:12
    user: root
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DEFAULT_TABLESPACE: ''
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /home/beehyv/Downloads/seed_data_dump_4.sql:/home/seed_data_dump_4.sql
      - /home/beehyv/Downloads/eg_mdms_schema_definitions_dump.sql:/home/seed_data_dump_ms.sql
      - /home/beehyv/Downloads/eg_mdms_data_dump.sql:/home/seed_data_dump_md.sql
  kafka:
    image: confluentinc/cp-kafka:7.1.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9094"
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch-6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: elasticsearch-6
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - thread_pool.write.queue_size=500
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es6-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana-6:
    image: docker.elastic.co/kibana/kibana:6.8.23
    container_name: kibana-6
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-6:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-6

volumes:
  postgres-data:
  redis-data:
  es-data:
  es6-data:
  kafka-data:
  zookeeper-data:
  config_data:

networks:
  esnet:
    driver: bridge