CREATE  Table eg_wms_loi(
  id varchar(256),
  tenantId varchar(64) NOT NULL,
  loi_number varchar(128) NOT NULL,
  work_pkg_number varchar(128) ,
  work_identification_number varchar(128),
  file_number varchar(128) NOT NULL,
  file_date bigint NOT NULL,
  negotiated_percentage numeric NOT NULL,
  agreement_date bigint NOT NULL,
  contractor_id varchar(256) NOT NULL,
  security_deposit numeric,
  bank_guarantee varchar(256),
  emd_amount numeric NOT NULL,
  contract_period numeric,
  defect_liability_period numeric NOT NULL,
  oic_id varchar(256) NOT NULL,
  status varchar(128) NOT NULL,
  letter_status varchar(128),
  additionaldetails jsonb,
  createdby varchar(64),
  lastmodifiedby varchar(64),
  createdtime bigint,
  lastmodifiedtime bigint,
  CONSTRAINT uk_eg_wms_loi UNIQUE (loi_number),
  CONSTRAINT pk_eg_wms_loi PRIMARY KEY (id)
);