openapi: 3.0.0
info:
  version: 1.0.0
  title: Expense Demand
  description: Capture the details for expense demands
paths:
  /demand/v1/_create:
    post:
      tags:
        - Demand
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemandRequest'
      responses:
        '202':
          description: Accepted account registration request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DemandResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /demand/v1/_update:
    post:
      tags:
        - Demand
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemandRequest'
      responses:
        '202':
          description: Accepted account updation request.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DemandResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /demand/v1/_search:
    post:
      tags:
        - Demand
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemandSearchRequest'
      responses:
        '200':
          description: Return search results
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DemandResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
components:
  schemas:
    Demand:
      description: A Object which holds the info about the expense details
      type: object
      properties:
        id:
          description: Unique identifier of the record
          readOnly: true
          type: string
          format: uuid
        tenantId:
          description: Tenant Identifier
          example: pb.amritsar
          type: string
          minLength: 2
          maxLength: 64
        demandType:
          description: Demand type enum
          type: string
          enum:
            - EXPENSE
        businessService:
          description: >-
            Capture the expense system unique identifier.(It's name spaced
            master data defined in MDMS)
          example: WORKS, SALARY etc
          type: string
          minLength: 2
          maxLength: 64
        referenceId:
          description: Pass reference to link multiple demands
          type: string
          minLength: 2
          maxLength: 64
        fromPeriod:
          description: Start date of demand period
          type: number
          format: timestamp
          minLength: 2
          maxLength: 64
        toPeriod:
          description: End date of demand period
          type: number
          format: timestamp
          minLength: 2
          maxLength: 64
        billGenDate:
          description: Bill generation date
          type: number
          format: timestamp
          minLength: 2
          maxLength: 64
        payee:
          $ref: '#/components/schemas/Party'
        payer:
          $ref: '#/components/schemas/Party'
        lineItems:
          type: array
          description: Line items of the demand
          items:
            $ref: '#/components/schemas/LineItems'
        additionalFields:
          description: Any additional details that need to be captured
          type: object
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
      required:
        - tenantId
        - demandType
        - businessService
        - lineItems
    Party:
      description: Account details
      type: object
      properties:
        type:
          description: Account holder name
          example: XYZ Holdings
          type: string
          minLength: 2
          maxLength: 64
        identifier:
          description: Unique bank account identifier of a individual/Org
          type: string
          minLength: 2
          maxLength: 64
      required:
        - type
        - identifier
    LineItems:
      description: Line items are the amount breakups for net amounts
      type: object
      properties:
        id:
          description: Unique identifier of the account
          readOnly: true
          type: string
          format: uuid
        tenantId:
          description: Tenant Identifier
          example: pb.amritsar
          type: string
          minLength: 2
          maxLength: 64
        headCode:
          description: Head codes are define master data
          example: BASICSALARY, HRA, INCOMETAX
          type: string
          minLength: 2
          maxLength: 64
        amount:
          description: amount for head code
          type: number
          minLength: 2
          maxLength: 64
        type:
          description: Type of line item
          type: string
          enum:
            - PAYABLE
            - DEDUCTION
        isActive:
          type: boolean
        additionalFields:
          description: Any additional details that need to be captured
          type: object
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
      required:
        - tenantId
        - headCode
        - amount
        - type
    DemandRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        demand:
          $ref: '#/components/schemas/Demand'
    DemandResponse:
      type: object
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        demands:
          type: array
          items:
            $ref: '#/components/schemas/Demand'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination
    DemandCriteria:
      type: object
      properties:
        tenantId:
          description: Tenant Identifier
          example: pg.cityA
          type: string
          minLength: 2
          maxLength: 64
        ids:
          type: array
          description: Search by demand ids
          format: uuid
          items:
            type: string
        businessService:
          description: >-
            Capture the expense system unique identifier.(It's name spaced
            master data defined in MDMS)
          example: WORKS, SALARY etc
          type: string
          minLength: 2
          maxLength: 64
        referenceId:
          description: >-
            Pass reference id to link multiple demands for single bill
            generation
          type: array
          format: uuid
          items:
            type: string
        isActive:
          type: boolean
      required:
        - tenantId
    DemandSearchRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        demandCriteria:
          $ref: '#/components/schemas/DemandCriteria'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination
