apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: IFMS-VA
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: IFMS-VA
            image: egovio/ifms-cronjob
            command: ["python3","cronJobAPIConfig.py"]
            args: ["VA"]  
            env:
              - name: TENANT_ID
                valueFrom:
                  configMapKeyRef:
                    name: egov-config
                    key: state-level-tenant-id
              - name: USER_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: egov-service-host
                    key: egov-user-egov
              - name: IFMS_ADAPTER_HOST
                valueFrom:
                  configMapKeyRef:
                    name: egov-service-host
                    key: ifms-adapter
          restartPolicy: OnFailure