const { createProxyMiddleware } = require('http-proxy-middleware');
const createProxy = createProxyMiddleware({
  target: process.env.REACT_APP_PROXY_URL,
  changeOrigin: true,
});
module.exports = function (app) {
  [
    '/egov-mdms-service',
    '/egov-location',
    '/localization',
    '/egov-workflow-v2',
    '/pgr-services',
    '/contract',
    '/filestore',
    '/egov-hrms',
    '/user-otp',
    '/user',
    '/fsm',
    '/billing-service',
    '/collection-services',
    '/pdf-service',
    '/pg-service',
    '/vehicle',
    '/vendor',
    '/property-services',
    '/fsm-calculator/v1/billingSlab/_search',
    '/muster-roll',
    '/project',
    '/inbox/v2/_search',
    '/individual',
    '/org-services',
    '/wms/contract/_search',
    '/contract',
    '/expensebilling',
    '/bankaccount-service',
    '/expense-calculator/v1/_estimate',
    '/expense-calculator/purchase/v1/_createbill',
    '/expense/bill/v1',
    '/egov-pdf/bill/_search',
    '/expense/bill',
    "/expense-calculator/v1/_search",
    "/expense/payment/v1/_create",
    "/expense-calculator/purchase/v1/_updatebill"
  ].forEach((location) => app.use(location, createProxy));
};
