@startuml
title: Expense Service - Payment Update Flow

actor user as "User" order 0 #ddff41
participant Expense as "Expense \nService" #4Ff2AF
queue KAFKA as "KAFKA" #4Ff2AF
participant Persister as "Persister" #4Ff2AF
database DB as "PostgreSQL" #4Ff2AF

user -> Expense: call /payment/v1/_create API (with bill list)
activate user #Fafd30
activate Expense #00ad00

Expense -> Expense: Validate payment request
note right: Validate required fields, bill list, \namounts, duplicate payments etc.

alt if validation fails
    Expense --> user: [400]: Invalid or missing payment details
end


note over Expense: Extract and prepare to enrich request

Expense -> Expense: Enrich payment request with\nUUIDs and audit details

Expense -> KAFKA: Push payment data to <b>expense-payment-update</b> topic
group Update paid amounts and payment status
    loop for each bill
        Expense -> Expense: Update bill's paid amount and payment status
        Expense -> KAFKA: Push bill data to <b>expense-bill-update</b> topic
    end
end
Expense --> user: [202]: Payment created successfully
deactivate Expense
deactivate user

group Save to DB: [async]
    KAFKA -> Persister: Consume payment payload
    Persister -> DB: Save payment records
    KAFKA -> Persister: Consume bill payload
    Persister -> DB: Update bill records
end

==Validations==
Expense -> DB: Get payment by id
activate Expense #F1aF0F
activate DB #008390
DB --> Expense: Return matching payments from DB
deactivate DB
alt if payment not exists
    Expense --> user: [400]: Payment not found
end

Expense -> DB: Check if bills exist in DB
activate DB #008390
DB --> Expense: Return matching bills from DB
deactivate DB

alt if any bill not found
    Expense --> user: [400]: One or more bills not found
end

' Create same for payment if payment already exists


'Amount to be paid should be less than bill amount
Expense -> Expense: Check if paid amount is less than bill amount
note over Expense: This will be performed at bill, bill details & lineitems
alt if paid amount exceeds bill amount
    Expense --> user: [400]: Amount to be paid exceeds the bill amount
end
@enduml
