package org.egov.digit.expense.util;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.egov.digit.expense.web.models.Bill;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

public class BillPeriodUtilTest {

    /** Periods are generated by epoch-ms stepping; the zone here only builds day-aligned fixtures. */
    private static final String ZONE = "Africa/Maputo";

    private BillPeriodUtil util;

    @BeforeEach
    void setUp() {
        util = new BillPeriodUtil(new ObjectMapper());
    }

    /** Period boundaries as health-expense-calculator writes them: start-of-day → end-of-day. */
    private Bill billWithPeriod(LocalDate from, LocalDate to) {
        ZoneId zone = ZoneId.of(ZONE);
        Map<String, Object> ad = new HashMap<>();
        ad.put("periodStartDate", from.atStartOfDay(zone).toInstant().toEpochMilli());
        ad.put("periodEndDate", to.atTime(23, 59, 59, 999_000_000).atZone(zone).toInstant().toEpochMilli());
        return Bill.builder().id("bill-1").additionalDetails(ad).build();
    }

    @Test
    void countsBothEndpoints() {
        assertEquals(28, util.resolveMaxAttendanceDays(
                billWithPeriod(LocalDate.of(2026, 2, 2), LocalDate.of(2026, 3, 1))));
    }

    @Test
    void singleDayPeriodIsOneDay() {
        assertEquals(1, util.resolveMaxAttendanceDays(
                billWithPeriod(LocalDate.of(2026, 2, 2), LocalDate.of(2026, 2, 2))));
    }

    @Test
    void endOfDayBoundaryDoesNotOvercount() {
        assertEquals(7, util.resolveMaxAttendanceDays(
                billWithPeriod(LocalDate.of(2026, 2, 2), LocalDate.of(2026, 2, 8))));
    }

    /**
     * Real billing period from hcm-demo (period 2 of CMP-2026-09-03-004616, 07–09 Sep 2026),
     * where the payments UI caps days worked at 3. These bounds are midnight-aligned in IST
     * while health-expense runs app.timezone=UTC — a calendar-date count in UTC yields 4.
     */
    @Test
    void matchesTheCeilingTheAttendanceUiEnforces() {
        Map<String, Object> ad = new HashMap<>();
        ad.put("periodStartDate", 1788719400000L);
        ad.put("periodEndDate", 1788978599999L);

        assertEquals(3, util.resolveMaxAttendanceDays(
                Bill.builder().id("bill-demo").additionalDetails(ad).build()));
    }

    @Test
    void noPeriodMeansNoCeiling() {
        assertNull(util.resolveMaxAttendanceDays(Bill.builder().id("b").build()));
        assertNull(util.resolveMaxAttendanceDays(
                Bill.builder().id("b").additionalDetails(new HashMap<String, Object>()).build()));
    }

    @Test
    void invertedPeriodMeansNoCeiling() {
        assertNull(util.resolveMaxAttendanceDays(
                billWithPeriod(LocalDate.of(2026, 3, 1), LocalDate.of(2026, 2, 2))));
    }

    @Test
    void periodDatesGivenAsStringsAreAccepted() {
        Map<String, Object> ad = new HashMap<>();
        ZoneId zone = ZoneId.of(ZONE);
        ad.put("periodStartDate",
                String.valueOf(LocalDate.of(2026, 2, 2).atStartOfDay(zone).toInstant().toEpochMilli()));
        ad.put("periodEndDate",
                String.valueOf(LocalDate.of(2026, 2, 8).atTime(23, 59).atZone(zone).toInstant().toEpochMilli()));
        assertEquals(7, util.resolveMaxAttendanceDays(
                Bill.builder().id("b").additionalDetails(ad).build()));
    }

    @Test
    void rangeTextDegradesWhenCeilingUnknown() {
        assertEquals("between 0 and 28", BillPeriodUtil.attendanceRangeText(28));
        assertEquals("0 or greater", BillPeriodUtil.attendanceRangeText(null));
    }
}
