apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily
            image: egovio/expense-cronjob
            command: ["python3","cronJobAPIConfig.py"]
            args: ["daily"]  
            env:
              - name: TENANT_ID
                valueFrom:
                  configMapKeyRef:
                    name: egov-config
                    key: state-level-tenant-id
              - name: MDMS_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: egov-service-host
                    key: egov-mdms-service
              - name: USER_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: egov-service-host
                    key: egov-user-egov
              - name: CONTRACTS_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: egov-service-host
                    key: contract-service
              - name: EXPENSE_CALCULATOR_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: egov-service-host
                    key: expense-calculator
          restartPolicy: OnFailure