name: Node.js Publish Contracts Package

on:
  push:
    branches: [ deploy ]
    paths:
      - 'frontend/micro-ui/web/micro-ui-internals/packages/modules/Contracts/**'
  pull_request:
    branches: 
      # Push events on main branch
      - 'master'
      # Push events to branches matching refs/heads/mona/octocat
      - 'develop'
      # Push events to branches matching refs/heads/releases/10
      - 'publish-**' 
    paths:
      - 'frontend/micro-ui/web/micro-ui-internals/packages/modules/Contracts/**'
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: cd frontend/micro-ui/web/micro-ui-internals/packages/modules/Contracts && yarn && yarn prepublish && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
