# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js CSS Package

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: 
      # Push events on main branch
      - 'master'
      # Push events to branches matching refs/heads/mona/octocat
      - 'develop'
      # Push events to branches matching refs/heads/releases/10
      - 'publish-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: cd frontend/micro-ui/web/micro-ui-internals/packages/css && yarn && yarn prepublish && npm publish --tag beta-2.7
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
