name: Docker Image CI

on:
  push:
    branches: [ "2307" ]
  pull_request:
    branches: [ "2307" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./frontend/micro-ui/web/docker/Dockerfile --tag works-ui:$(date +%s)
