# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Publish libraries Package

on:
  push:
    branches:
      # Push events on main branch
      - 'deploy'
      # Push events to branches matching refs/heads/releases/10
      - 'inter-**'
  pull_request:
    branches: 
      # Push events on main branch
      - 'master'
      # Push events to branches matching refs/heads/mona/octocat
      - 'develop'
      # Push events to branches matching refs/heads/releases/10
      - 'publish-**'    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: cd frontend/micro-ui/web/micro-ui-internals/packages/libraries && yarn && yarn prepublish && npm publish --tag beta-2.7
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
