FROM egovio/flyway:4.1.2

COPY ./migration/main /flyway/sql

COPY migrate.sh /usr/bin/migrate.sh

RUN chmod +x /usr/bin/migrate.sh

COPY ./../cacerts /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/cacerts

CMD ["/usr/bin/migrate.sh"]
